services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $keyDirectory: "%shapecode_doctrine_encrypt.secret_directory%"
            $defaultEncryptor: "%shapecode_doctrine_encrypt.encryptor%"

    _instanceof:
        Shapecode\NYADoctrineEncryptBundle\Encryption\Encryptor\EncryptorInterface:
            tags: ['doctrine.encryptor']

    Shapecode\NYADoctrineEncryptBundle\Encryption\:
        resource: '../../Encryption/Encryption/*'

    Shapecode\NYADoctrineEncryptBundle\Encryption\Encryptor\:
        resource: '../../Encryption/Encryptor/*'

    Shapecode\NYADoctrineEncryptBundle\EventListener\DoctrineEncryptSubscriber:
        tags: ['doctrine.event_subscriber']

    Shapecode\NYADoctrineEncryptBundle\Command\:
        resource: '../../Command/*'
