services:

    shapecode_doctrine_encrypt.encryption.manager:
        class: Shapecode\NYADoctrineEncryptBundle\Encryption\EncryptionManager
        public: true
        arguments:
            - "%shapecode_doctrine_encrypt.encryptor%"

    shapecode_doctrine_encrypt.encryption.handler:
        class: Shapecode\NYADoctrineEncryptBundle\Encryption\EncryptionHandler
        public: true
        arguments:
            - '@annotation_reader'
            - "@shapecode_doctrine_encrypt.encryption.manager"

    doctrine.encryption:
        alias: shapecode_doctrine_encrypt.encryption.handler

    # encryptors
    shapecode_doctrine_encrypt.encryptor.defuse:
        class: Shapecode\NYADoctrineEncryptBundle\Encryption\Encryptor\DefuseEncryptor
        public: false
        arguments:
          - "%shapecode_doctrine_encrypt.secret_key_path%"
        tags:
            - { name: doctrine.encryptor }

    shapecode_doctrine_encrypt.encryptor.halite:
        class: Shapecode\NYADoctrineEncryptBundle\Encryption\Encryptor\HaliteEncryptor
        public: false
        arguments:
          - "%shapecode_doctrine_encrypt.secret_key_path%"
        tags:
            - { name: doctrine.encryptor }

    # event listener
    shapecode_doctrine_encrypt.event_listener.doctrine_encrypt:
        class: Shapecode\NYADoctrineEncryptBundle\EventListener\DoctrineEncryptSubscriber
        public: true
        arguments:
            - "@shapecode_doctrine_encrypt.encryption.handler"
        tags:
            -  { name: doctrine.event_subscriber }

    # commands
    shapecode_doctrine_encrypt.command.status:
        class: Shapecode\NYADoctrineEncryptBundle\Command\StatusCommand
        public: false
        arguments:
            - '@doctrine'
            - '@doctrine.encryption'
            - '@shapecode_doctrine_encrypt.encryption.manager'
            - '@shapecode_doctrine_encrypt.event_listener.doctrine_encrypt'
            - '@annotation_reader'
        tags:
            - { name: console.command }

    shapecode_doctrine_encrypt.command.encrypt:
        class: Shapecode\NYADoctrineEncryptBundle\Command\EncryptCommand
        public: false
        arguments:
            - '@doctrine'
            - '@doctrine.encryption'
            - '@shapecode_doctrine_encrypt.encryption.manager'
            - '@shapecode_doctrine_encrypt.event_listener.doctrine_encrypt'
            - '@annotation_reader'
        tags:
            - { name: console.command }

    shapecode_doctrine_encrypt.command.decrypt:
        class: Shapecode\NYADoctrineEncryptBundle\Command\DecryptCommand
        public: false
        arguments:
            - '@doctrine'
            - '@doctrine.encryption'
            - '@shapecode_doctrine_encrypt.encryption.manager'
            - '@shapecode_doctrine_encrypt.event_listener.doctrine_encrypt'
            - '@annotation_reader'
        tags:
            - { name: console.command }
