services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Shapecode\NYADoctrineEncryptBundle\Encryption\Encryptor\EncryptorInterface:
            tags: ['doctrine.encryptor']

    Shapecode\NYADoctrineEncryptBundle\Encryption\EncryptionManagerInterface: '@Shapecode\NYADoctrineEncryptBundle\Encryption\EncryptionManager'
    Shapecode\NYADoctrineEncryptBundle\Encryption\EncryptionManager:
        arguments:
            $default: "%shapecode_doctrine_encrypt.encryptor%"

    Shapecode\NYADoctrineEncryptBundle\Encryption\EncryptionHandler: ~
    Shapecode\NYADoctrineEncryptBundle\Encryption\EncryptionHandlerInterface: '@Shapecode\NYADoctrineEncryptBundle\Encryption\EncryptionHandler'

    # encryptors
    Shapecode\NYADoctrineEncryptBundle\Encryption\Encryptor\DefuseEncryptor:
        arguments:
            $keyFile: "%shapecode_doctrine_encrypt.secret_directory%"

    Shapecode\NYADoctrineEncryptBundle\Encryption\Encryptor\HaliteEncryptor:
        arguments:
            $keyFile: "%shapecode_doctrine_encrypt.secret_directory%"

    # event listener
    Shapecode\NYADoctrineEncryptBundle\EventListener\DoctrineEncryptSubscriber:
        tags: ['doctrine.event_subscriber']

    # commands
    Shapecode\NYADoctrineEncryptBundle\Command\StatusCommand: ~
    Shapecode\NYADoctrineEncryptBundle\Command\EncryptCommand: ~
    Shapecode\NYADoctrineEncryptBundle\Command\DecryptCommand: ~
